apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt-deployment
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: demo
          image: demo
          imagePullPolicy: IfNotPresent
          env:
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  name: demo-cm
                  key: token
          ports:
            - containerPort: 9000
